<a href="https://colab.research.google.com/github/PraeJi/Python-Practice/blob/master/3_01_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow Basic

In [ ]:
import tensorflow as tf
import numpy as np

## Creating a tensor

In [ ]:
x = tf.constant([[1.,3.,0.],
                 [0.,1.,2.],
                 [1.,0.,1.]]) # a nested list
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 3., 0.],
       [0., 1., 2.],
       [1., 0., 1.]], dtype=float32)>

## Conducting mathematical operations

In [ ]:
print(x + x)
print(5 * x)

tf.Tensor(
[[2. 6. 0.]
 [0. 2. 4.]
 [2. 0. 2.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 5. 15.  0.]
 [ 0.  5. 10.]
 [ 5.  0.  5.]], shape=(3, 3), dtype=float32)


In [ ]:
print(x @ tf.transpose(x)) # @ represent matrix multiplication ==> x(xt)

tf.Tensor(
[[10.  3.  1.]
 [ 3.  5.  2.]
 [ 1.  2.  2.]], shape=(3, 3), dtype=float32)


In [ ]:
print(tf.concat([x,x,x], axis=0)) # 0 mean row
print(tf.concat([x,x,x], axis=1)) # 1 mean column

tf.Tensor(
[[1. 3. 0.]
 [0. 1. 2.]
 [1. 0. 1.]
 [1. 3. 0.]
 [0. 1. 2.]
 [1. 0. 1.]
 [1. 3. 0.]
 [0. 1. 2.]
 [1. 0. 1.]], shape=(9, 3), dtype=float32)
tf.Tensor(
[[1. 3. 0. 1. 3. 0. 1. 3. 0.]
 [0. 1. 2. 0. 1. 2. 0. 1. 2.]
 [1. 0. 1. 1. 0. 1. 1. 0. 1.]], shape=(3, 9), dtype=float32)


In [ ]:
print(tf.reduce_sum(x)) # sum all
print(tf.reduce_sum(x, axis=0)) # sum follow by row
print(tf.reduce_sum(x, axis=1)) # sum follow by column

tf.Tensor(9.0, shape=(), dtype=float32)
tf.Tensor([2. 4. 3.], shape=(3,), dtype=float32)
tf.Tensor([4. 3. 2.], shape=(3,), dtype=float32)


In [ ]:
# softmax function
print(tf.nn.softmax(x, axis=-1)) # -1 mean claculate softmax in the last dimention

tf.Tensor(
[[0.11419519 0.8437947  0.04201007]
 [0.09003057 0.24472848 0.66524094]
 [0.42231882 0.15536241 0.42231882]], shape=(3, 3), dtype=float32)


## Variables

In [ ]:
w = tf.Variable([0.1, 0.0, 0.1])
w.assign([1.0,0.1,1.2]) # replace all values
w.assign_add([0.1,0.1,0.1]) # +=

<tf.Variable 'UnreadVariable' shape=(3,) dtype=float32, numpy=array([1.1      , 0.2      , 1.3000001], dtype=float32)>

# Automatic Differentation

In [ ]:
w = tf.Variable(1.5)
b = tf.Variable(1.0)
x = tf.Variable(2.0)

In [ ]:
with tf.GradientTape() as tape:
  z = tf.nn.sigmoid(w*x + b)
tf.print(z)

z_ = tape.gradient(z, [w,b])

tf.print(z_)

# output ==> [dz/dw, dz/db]

0.982013762
[0.0353254676, 0.0176627338]
